### ISSUE TITLE
"and" language chain not working on v4.2.0

### ISSUE THREAD

**Issue by dnoliver** [domenic/chai-as-promised#85] opened 2015-02-18 18:56 UTC
I had some mocha tests with chai + chai-as-promised as assertion lib. I was using older versions of them: 
```
"chai":"1.6.1"
"chai-as-promised":"3.3.1"
```
After a little update to the following version: 
```
"chai":"2.0.0"
"chai-as-promised":"4.2.0"
```
some of the test that use the "and" language chain  stop working. The following test was working properly with the older version of the libs, and stop working with the new ones: 
```
expect(someQpromise).
to.eventually.have.property('foo','foo')
.and.have.property('bar','bar')
.and.notify(done);
```

**Comment by domenic** [comment] 2015-03-05 23:19
Yeah, I can see how this might have fallen through the cracks in the great 4.0.0 rewrite. I can try to look in to it, although I'm not sure it'll be easy... pull request certainly welcome.

**Comment by DerekDomino** [comment] 2015-06-18 14:51
Neither on 5.1.0. Here are my troubles:

````
return my_promise.should.eventually.have.deep.property('errors[0].params'); // OK, fails if params not present
return my_promise.should.eventually.have.deep.property('errors[0].params').that.is.an('array'); // KO, does not fail when params not present
return my_promise.should.eventually.have.deep.property('errors[0].params').with.length.of(2); // KO, does not fail when assertion is not verified
````

Am I using the chaijs rules with chai-as-promised correctly?

If so, I think, the following Readme statement 
````
With it [`eventually`], you can transform any existing Chai assertion
into one that acts on a promise
````
should be rephrased as follows:
````
With it  [`eventually`], you can transform some of Chai assertions
into assertions that acts on a promise
````

**Comment by dnoliver** [comment] 2015-06-18 15:13
Right, we had to change our tests to use the following syntax with the "and" language chain: 
 
        var db = {
          users: {
            johndoe: {
              name: 'John',
              lastname: 'Doe'
            }
          },
          apps: {
            111: {}
          }
        };
        
        expect(db).to.have.property('users').and.have.property('johndoe').and.have.property('name','John');
        // note that the second assertion is performed over the db.users property
        // and the third one is over db.users.johndoe user. Do not use 'and' to make several assertions over
        // the same property. 
        
        // this whould fail with latest chai version
        expect(db).to.have.property('users').and.have.property('apps');
        
        // the above spec should be written as follow
        expect(db).to.have.property('users');
        expect(db).to.have.property('apps');

**Comment by domenic** [comment] 2015-06-18 15:52
> If so, I think, the following Readme statement 

Pull request welcome, pointing to this bug as the cause.

**Comment by DerekDomino** [comment] 2015-06-18 16:54
After some investigation, above assertions work :-) 
However, it seems that assertion ordering is not preserved when testing several of them with q.all().

The following test works as expected: mismatch between array length and expected length is raised
````
// Promise to be tested
var validate_promise = q({
    content: [0,1]
});


// Queue of tests
var test_promises = [];

// Push 1 test in promise queue
test_promises.push(
    validate_promise.should.eventually.have.property('content').that.is.an('array').with.length.of(3),
    validate_promise.should.eventually.have.deep.property('content[0]', 0)
);

return q.all(test_promises); 
````
It results in `AssertionError: expected [ 0, 1 ] to have a length of 3 but got 2`: Excellent!


Now, just change the expected value of `content` in the second assertion in the queue
````
// Promise to be tested
var validate_promise = q({
    content: [0,1]
});


// Queue of tests
var test_promises = [];

// Push 2 tests in promise queue
test_promises.push(
    validate_promise.should.eventually.have.property('content').that.is.an('array').with.length.of(3),
    validate_promise.should.eventually.have.deep.property('content[0]', 1)
);

return q.all(test_promises); 
````
It results in `AssertionError: expected { content: [ 0, 1 ] } to have a deep property 'content[0]' of 1, but got 0`. The expected `AssertionError` should be again the related the 1st assertion (`length.of`).

**Comment by domenic** [comment] 2015-07-01 02:18
Promise.all/Q.all are inherently unordered though. They run things in parallel---whichever failure happens first will trigger.

If you want sequential all, you can write a separate utility function for that.

**Comment by jacobdr** [comment] 2015-12-21 17:51
I'm still having related issues....

For example, I have a test 
`documentToCheckPromise.should.eventually.have.deep.property('process.resize.current.enqueued.actor').that.is.a('string').with.length.above(10)`

This does not work, but the below does: 

`documentToCheckPromise.should.eventually.have.deep.property('process.resize.current.enqueued').and.property('actor').that.is.a('string').and.is.not.empty`

And yet this does not work:
`documentToCheckPromise.should.eventually.have.deep.property('process.resize.current.enqueued').and.property('actor').that.is.a('string').and.has.length.above(0)`

Does anyone have any advice? I seem to be struggling with both chainable length(s) and the 'deep property' assertions...

Thanks. JR

**Comment by romeovs** [comment] 2016-05-19 16:23
I'm also running into this:

```
expect(db.find({email: email}))
  .to.eventually.have.property('email', email)
  .and.have.property('valid', false)
  .and.notify(done)
```

Because this is run inside a callback, I cannot use `return` to return the promise, and need to use the `done` callback. Which makes it harder to use `Promise.all` to group the assertions.

**Comment by lddubeau** [comment] 2016-09-12 12:33
This bug report came up in discussion regarding #166. I've tried reproducing the issues with the fragments of code shown in the initial report and the comments posted after it and I just cannot reproduce them using Chai 3.5.0 and chai-as-promised 5.3.0.

If those who posted here still have a problem attributable to chai-as-promised, and they want the issue to be investigated while work on #166 is happening, please post a [MCVE](http://stackoverflow.com/help/mcve). State the behavior you are getting and the behavior you are expecting.

**Comment by domenic** [comment] 2016-10-08 22:22
It looks like this is probably fixed, if not earlier, at least due to @lddubeau's work in v6.0.0. So, closing. Happy to reopen if people have small repro cases.

**Closed by domenic** 2016-10-08 22:22 UTC
Labels: bug
