### ISSUE TITLE
Update license

### ISSUE THREAD

**Issue by donvadicastro** [domenic/chai-as-promised#187] opened 2017-03-28 14:19 UTC
We can't use this library with next license content:

This work is free. You can redistribute it and/or modify it under the
terms of the Do What The Fuck You Want To Public License, Version 2,
as published by Sam Hocevar. See below for more details.

        DO WHAT THE FUCK YOU WANT TO PUBLIC LICENSE
                    Version 2, December 2004

**Comment by Croydon** [comment] 2017-04-12 20:32
Please relicense under CC-0 1.0 or MIT or another bullet proofed open source license.

**Comment by domenic** [comment] 2017-06-11 17:48
Dupe of #176.

**Closed by domenic** 2017-06-11 17:48 UTC
