### ISSUE TITLE
to.be.resolved vs. to.be.fulfilled

### ISSUE THREAD

**Issue by maximilianschmitt** [domenic/chai-as-promised#106] opened 2015-04-21 12:37 UTC
Hi! I've stumbled over this little thing many times across different projects. The first time it happened, it took me hours to find the issue.

I often think of Promises as being `resolved` instead of `fulfilled`. This probably comes from the name of the `Promise.resolve` function. Sometimes in my tests, I mistakenly use `to.be.resolved` which results in really weird behaviour.

```js
describe('chai-as-promised-gotcha', function() {
  it('resolves even though it is rejected', function() {
    return expect(reject()).to.be.resolved;
  });

  it('works if you use `fulfilled` instead of `resolved`', function() {
    return expect(reject()).to.be.fulfilled;
  });

  function reject() {
    return Promise.reject(new Error());
  }
});
```

```
  chai-as-promised-gotcha
    ✓ resolves even though it is rejected
    1) works if you use `fulfilled` instead of `resolved`


  1 passing (27ms)
  1 failing

  1) chai-as-promised-gotcha works if you use `fulfilled` instead of `resolved`:
     AssertionError: expected promise to be fulfilled but it was rejected with [Error]
```

If there was a way to make `to.be.resolved` work as `to.be.fulfilled` or throw an error if `to.be.resolved` is being used, I think that would be great.

Apart from this small but annoying issue, I really love this library and use it a lot. It really makes testing asynchronous functions as easy as testing synchronous functions. So thanks a lot for this awesome project! :)

**Comment by keithamus** [comment] 2015-04-21 14:23
Makes sense to me. Feel free to make a PR making an alias to the resolved function, and given @domenic's blessing, I'd happily merge it.

**Comment by domenic** [comment] 2015-04-21 14:42
Nope. Dupe of #91. Resolved and fulfilled are extremely different.

**Closed by domenic** 2015-04-21 14:42 UTC
Labels: enhancement

**Comment by maximilianschmitt** [comment] 2015-04-21 14:46
Ah, thanks for clarifying. It looks like `to.be.resolved` works as expected then. Thanks!
