### ISSUE TITLE
rejectedWith does not work with custom error

### ISSUE THREAD

**Issue by mdotasia** [domenic/chai-as-promised#159] opened 2016-06-30 21:35 UTC
I am on Node 6.2.1 and use ES2015 syntax (whatever is supported). I'm writing a CLI tool and I have two occasions where I reject a promise with a custom error (with different messages):

```
reject(new NoMatchingFilesError('No matching tweet files in directory.'));
```

with `NoMatchingFilesError` being defined as

```
class NoMatchingFilesError extends Error {
  constructor(message) {
    super(message);
    this.name = this.constructor.name;
    this.message = message;
    Error.captureStackTrace(this, this.constructor.name);
  }
}
```

There are 2 corresponding unit tests that look like this (different messages):

```
it('should reject promise with NoMatchingFilesError', () => evaluation.getSinceId({
  list: 'dummy',
  user: 'dummy',
}).should.be.rejectedWith(NoMatchingFilesError, 'No matching tweet files in directory.'));
```

When I run the tests the first test fails and the second test passes.

I tracked the issue down to this line: https://github.com/domenic/chai-as-promised/blob/master/lib/chai-as-promised.js#L192. The test fails because `reason instanceof Constructor` evaluates to `false` for the first test. The second one evaluates to `true`.

In `node-debug` I see no difference: In both cases the `Constructor` looks fine and the prototype chains looks fine, and yet one test fails. When I rewrite my code use `Error` instead of custom `NoMatchingFilesError` both tests pass.

Any idea what's going wrong here?

This might be related to https://github.com/domenic/chai-as-promised/issues/113.

**Comment by domenic** [comment] 2016-06-30 21:43
If you can produce a small, 10-20 line reproduction case I can run standalone with no dependencies, I can test this more easily.

**Comment by domenic** [comment] 2016-08-05 13:46
Closing due to lack of small repro case.

**Closed by domenic** 2016-08-05 13:46 UTC
