### ISSUE TITLE
TypeError from chai-as-promised

### ISSUE THREAD

**Issue by charlesb-yesmail** [domenic/chai-as-promised#177] opened 2016-12-07 17:51 UTC
I am seeing an error which I can't explain when using chai-as-promised in a mocha test suite.  I have two unit tests which are identical except for the type of assertion they do.

The following example works:

```javascript
    it('defaults to GET method', function() {
      baseUrl = 'http://httpstat.us';
      resource = '/200';
      reqConfig = {
        uri: format('{0}{1}', baseUrl, resource),
        headers: headers
      }
      nock(baseUrl)
      .get(resource)
      .reply(200, '200 OK');
      var result = HttpRequest.submit(reqConfig).then(function(response) {
        log.debug('response: %s', JSON.stringify(response));
        return response.statusCode;
      });
      return expect(result).to.eventually.equal(200);
    });
```

The following example fails:

```javascript
    it('supports GET method', function() {
      baseUrl = 'http://httpstat.us';
      resource = '/200';
      reqConfig = {
        method: 'GET',
        uri: format('{0}{1}', baseUrl, resource),
        headers: headers
      }
      nock(baseUrl)
      .get(resource)
      .reply(200, '200 OK');
      var result = HttpRequest.submit(reqConfig).then(function(response) {
        log.debug('response: %s', JSON.stringify(response));
        return response;
      });
      return expect(result.statusCode).to.eventually.equal(200);
    });
```

The HttpRequest.submit method returns a Promise which contains the a JSON object containing the response from submitting an HTTP request using request-promise.

The difference between the two test cases is that the top example is returning a specific value from the response object which is then used in the chai-as-promised assertion, whereas the bottom example is returning the entire response object and then I try to reference the properties of the object within the chai-as-promised assertion.

The second example fails with the following error:

```
  1) HttpRequest #submit supports GET method:
     TypeError: Cannot read property 'then' of undefined
      at assertIsAboutPromise (node_modules/chai-as-promised/lib/chai-as-promised.js:28:34)
      at null.<anonymous> (node_modules/chai-as-promised/lib/chai-as-promised.js:47:13)
      at addProperty (node_modules/chai/lib/chai/utils/addProperty.js:43:29)
      at Context.<anonymous> (test/model/api/http-request.test.js:48:42)
```

I need to be able to return the whole response object back to the assertion layer so that I can write assertions which use multiple properties from it in more complex test cases.

These are the versions I am using:

```
├── chai@3.5.0
├── chai-as-promised@6.0.0
└── mocha@3.2.0
```

Can you advise what may be happening here?

**Comment by keithamus** [comment] 2016-12-08 00:10
Hey @charlesb-yesmail thanks for the issue. I think the problem is here:

```js
return expect(result.statusCode).to.eventually.equal(200);
```

If `result` is `instanceof Promise`, then `result.statusCode` will be undefined, and `undefined` has no `then` method. Hence the error `Cannot read property 'then' of undefined`. I think you probably want to express this as:

```js
return expect(result).to.eventually.have.property('statusCode', 200);
```

They key difference here - is that you're `expect`ing on the Promise value. It might be more readable to rename `result` to `promise` or `eventualResult`.

I hope this fixes your issue, I have a hunch it will so I'll close this issue for now - but if you're still having the problem, please do let us know and we'll re-open it! Happy coding!

**Closed by keithamus** 2016-12-08 00:10 UTC

**Comment by charlesb-yesmail** [comment] 2016-12-08 08:27
Hi @keithamus,

That has fixed the problem - thanks for the swift reply.

Charles.

**Comment by charlesb-yesmail** [comment] 2016-12-08 12:47
A follow up question.  I realised that I actually need to assert against the value of a property of a sub object in the object returned within the Promise.  For example:

```javascript
{
	statusCode: 200,
	body: {
		property1: 'foo'
	}
}
```
How can I assert that `body.property1` equals 'foo'?  I tried this:

```return expect(result).to.eventually.have.property('body.property1', 'foo');```

but that doesn't appear to work.

**Comment by keithamus** [comment] 2016-12-08 16:55
If you're using Chai@3.5.0 you'll need to add _deep_:

```js
return expect(result).to.eventually.have.deep.property('body.property1', 'foo');
```

If you're using Chai@canary, aka Chai@4.0.0 you'll need to add _nested_:


```js
return expect(result).to.eventually.have.nested.property('body.property1', 'foo');
```

**Comment by charlesb-yesmail** [comment] 2016-12-08 17:08
Works beautifully - thanks!
