### ISSUE TITLE
rejectedWith cannot be used with Boom errors

### ISSUE THREAD

**Issue by DominikPalo** [domenic/chai-as-promised#200] opened 2017-06-07 19:36 UTC
In my API I use [Boom](https://github.com/hapijs/boom) as a helper for HTTP errors. But testing of this kind of errors is not possible - it still fails although thrown errors are the same as expected. Example:

```
import * as boom from 'boom';
import { use, expect } from 'chai';
import * as chaiAsPromised from 'chai-as-promised';

use(chaiAsPromised);

describe('demo test', function() {
    it('should pass', async function() {
      const foo = async function () {
        throw boom.notFound();
      };

      return expect(foo()).to.be.rejectedWith(boom.notFound());
    });
}
```

fails with message:

> AssertionError: expected promise to be rejected with 'Error: Not Found' but it was rejected with 'Error: Not Found'

**Comment by domenic** [comment] 2017-06-07 20:02
When I try to run that in Node.js I get SyntaxErrors because of the unrecognized `import` syntax. So, I am unable to debug this issue for you, and thus unable to help.

**Comment by DominikPalo** [comment] 2017-06-07 20:10
Ok, so here is it rewritten using legacy require syntax instead of ES6 imports:
```
const boom = require('boom');
const chai = require('chai');
const chaiAsPromised = require('chai-as-promised');

chai.use(chaiAsPromised);

describe('demo test', function() {
  it('should pass', async function() {
    const foo = async function () {
      throw boom.notFound();
    };

    return chai.expect(foo()).to.be.rejectedWith(boom.notFound());
  });
}
```

**Comment by meeber** [comment] 2017-06-07 20:14
@DominikPalo It looks like `boom.notFound()` returns an new instance of an `Error` object. When provided with an `Error` object, Chai's `throw` assertion checks to see if the `Error` object thrown by the function is strictly (`===`) equal to the `Error` object that was passed to it. Because two separate `Error` objects are created by two separate calls to `boom.notFound()` in your example, they're considered different.

I'm thinking your best option is to compare error messages instead. It doesn't look like Boom extends the `Error` object or anything for its various error types, so relying on `throw`'s use of `instanceof` wouldn't work either.

More info on Chai's `.throw` assertion (which `.rejectedWith` is based on) is available [here](http://chaijs.com/api/bdd/#method_throw).

**Comment by DominikPalo** [comment] 2017-06-07 20:24
Thanks for explanation, but in another project I'm using [Should.js](https://shouldjs.github.i) -> [rejectedWith](https://shouldjs.github.io/#assertion-rejectedwith) and it works without problems also with Boom errors (I don't know how Should.js works under the hood) - maybe it could be fine to get some inspiration how it is implemented in Should.js project.

**Comment by meeber** [comment] 2017-06-07 20:59
@DominikPalo What should.js does in that situation is perform a deep equality comparison between the error objects, rather than Chai's behavior of performing a strict equality comparison. This difference in behavior between the libraries fulfills two different use cases. For the Boom.js use case, should.js's behavior is more compatible than Chai.js's behavior.

Chai.js defaults to strict equality across all of its assertions. One idea would be to propose a change that the `deep` flag interact with the `.throw` assertion to allow deep equality to be used instead. If you want to pursue this, then I recommend opening a ticket on Chai's issue tracker and linking back to this one. Alternatively, you can open a ticket on Chai's issues tracker to make the argument that Chai should use deep equality by default in that situation.

**Comment by domenic** [comment] 2017-06-11 17:44
Thanks for the explanation and help @meeber. I'll close this since this is working as intended (i.e. working the same way as Chai).

**Closed by domenic** 2017-06-11 17:44 UTC

**Comment by zveljkovic** [comment] 2018-10-12 22:45
Just for anybody searching this issue, here's a start up code that can be used to create own helper.

```const chai = require('chai');
chai.use((chaiz, utils) => {
	const Assertion = chaiz.Assertion;
	Assertion.addMethod('throwError', function(errorFunction) {
		const basePromise: Promise<any> = typeof this.then === 'function' ? this : this._obj;
		this.assert(
			typeof basePromise.then === 'function',
			'expected promise parameter',
			'expected promise parameter',
		);
		const derivedPromise = basePromise.then(
			(value) => {
				this.assert(
					false,
					'expected ' + utils.inspect(value) + ' to be a ' + errorFunction.errorName,
					'expected ' + utils.inspect(value) + ' to not be a ' + errorFunction.errorName,
				);
			},
			(error) => {
					this.assert(
						error.name === errorFunction.errorName,
						'expected ' + error.name + ' to be a ' + errorFunction.errorName,
						'expected ' + error.name + ' to not be a ' + errorFunction.errorName,
					);
					return error;
				// } catch (reason) {
				// 		throw new chai.AssertionError(`${error.name}\n\nOriginal reason: ${utils.inspect(reason)}`);
				// }
		});
		this.then = derivedPromise.then.bind(derivedPromise);
		return this;
	});
});
```

Usage is like 
```
await expect(service.create(data as any)).to.throwError(appErrors.NotFoundError);
```
