### ISSUE TITLE
fulFilled.and.eventually is not supported

### ISSUE THREAD

**Issue by CodeTroopers** [domenic/chai-as-promised#185] opened 2017-03-17 09:50 UTC
I would like chain conditions on promise.
The below case test fails with 

> Cannot read property 'and' of undefined

```
bdd.it("test", function () {
	var promise = q.promise(function (resolve, reject, notify) {
		resolve([]);
	});
	return promise.should.be.fulFilled.and.eventually.be.an("array");
});
```

althought the chaining of conditions with rejection works:
```
bdd.it("test", function () {
	var promise = q.promise(function (resolve, reject, notify) {
		var error = new Error();
		error.code = 20;
		reject(error);
	});
	return promise.should.be.rejectedWith(Error).and.eventually.have.property("code").equal(20);
});
```

**Comment by keithamus** [comment] 2017-03-17 09:57
Hey @CodeTroopers thanks for the issue.

You don't need to add `fulFilled` to an `eventually`, as it is implied. Assert _either_ that a promise is `.fulFilled` (or `.not.fulFilled), or assert that it `eventually` will pass some additional assertions.

I'll close this issue, because I believe the code is working as intended. Feel free to discuss this further though, we can always re-open if needed.

**Closed by keithamus** 2017-03-17 09:57 UTC

**Comment by CodeTroopers** [comment] 2017-03-17 10:32
Ok but it is not very understanding : `fulFilled` is implied with `eventually` but `eventually` is also used in rejection case:
`return promise.should.be.rejectedWith(Error).and.eventually.have.property("code")`

**Comment by keithamus** [comment] 2017-03-17 12:05
IIRC the `eventually` is redundant in that instance, it is just as much to say

```js
return promise.should.be.rejectedWith(Error).with.property("code")
```

**Comment by CodeTroopers** [comment] 2017-03-17 15:13
It's not true!
This test case fail with 

> expected { state: 'pending' } to have a property 'code'

```
bdd.it("test", function () {
	var promise = q.promise(function (resolve, reject, notify) {
		setTimeout(function () {
			var error = new Error();
			error.code = 20;
			reject(error);
		}, 500);
	});
	return promise.should.be.rejectedWith(Error).and.have.property("code").equal(20);
});
```

althought with `eventually` it's works
```
bdd.it("test", function () {
	var promise = q.promise(function (resolve, reject, notify) {
		setTimeout(function () {
			var error = new Error();
			error.code = 20;
			reject(error);
		}, 500);
	});
	return promise.should.be.rejectedWith(Error).and.eventually.have.property("code").equal(20);
});
```

So there is  a real confusion between `fulFilled` implied with `eventually` and `eventually` usable in rejection case

**Comment by meeber** [comment] 2017-03-17 22:29
@CodeTroopers The reason your original example doesn't work is because the assertion is named `fulfilled` not `fulFilled`.

In Chai v4, which isn't officially released yet but available on npm via `chai@canary`, you would've received this more helpful error message:

> Error: Invalid Chai property: fulFilled. Did you mean "fulfilled"?

**Comment by keithamus** [comment] 2017-03-17 23:02
Oh...! I missed that!

**Comment by CodeTroopers** [comment] 2017-03-20 08:58
Arf! Now it's more clear in my head!
Thanks for your help guys. And sorry to have made you waste time on an error of copy
